# a lil' watch over dependencies

version: 2
updates:
  # for pip
  #--------
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # in root repository
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "ManonMarchand"

  # for github actions
  #-------------------
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # in .github/workflows
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "ManonMarchand"
