default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.8
repos:
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
    -   id: markdownlint
        args:
          [
            "--disable=MD013",
            "--disable=MD047"
          ]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
    -   id: nbqa-black
        name: nbqa-black
        description: "Run 'black' on a Jupyter Notebook"
        entry: nbqa black
        language: python
        require_serial: true
        types: [jupyter]
        additional_dependencies: [black]
    -   id: nbqa-flake8
        name: nbqa-flake8
        description: "Run flake8 on a Jupyter notebook"
    
