[tool.poetry]
name = "cds-tutorials"
version = "0.1.0"
repository = "https://github.com/cds-astro/tutorials"
description = "a repository of Jupyter Notebook tutorials using astronomical databases and virtual observatory tools"
authors = ["Manon Marchand <manon.marchand@astro.unistra.fr>"]
maintainers = ["Manon Marchand <manon.marchand@astro.unistra.fr>"]
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["astronomy", "tutorials", "virtual-observatory"]

[tool.nbqa.md]
blacken-docs = true
